name: SpaceBugUtils
version: 3.1
main: me.becja10.SpaceBugUtils.SpaceBugUtils
softdepend: [Essentials]
description: Additional Utilities for play.minecraft.dk
commands:
  silenttp:
    description: teleports someone to you without alerting them (used for AFK cheaters)
    usage: /<command> [player]
  onlinelongest:
    description: sorts the TAB list 
    usage: /<command>
    aliases: [ol]
  sbureload:
    description: reloads the plugin
    usage: /<command>
  sbspectate:
    description: Toggles spectate mode on or off
    usage: /<command>
    aliases: [sbs]
  sbnick:
    description: Changes someone's nickname.
    usage: /<command> <target> <nickname>
    aliases: [sbn]
  increasehomes:
    description: wrapper around increasing number of sethomes
    usage: /<command> <target> <homeNode>
  sayraw:
    description: Sends the provided message to all online players
    usage: /sayraw <message>
